/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./AboutSection.module.css";

function AboutSection() {
  return (
    <section className={styles.aboutSection}>
      <h2 className={styles.sectionTitle}>WHO WE ARE</h2>
      <p className={styles.description}>
        At Frithcode, we are a team of passionate innovators dedicated to
        transforming the educational landscape. Our expertise lies in developing
        cutting-edge school management systems that simplify and enhance the
        administrative processes of educational institutions.
      </p>
      <h2 className={styles.sectionTitle}>OUR VISION</h2>
      <p className={styles.description}>
        We envision a world where technology seamlessly integrates with
        education making it easier for schools to manage their operations and
        focus on what truly matters – educating and inspiring the next
        generation.
      </p>
    </section>
  );
}

export default AboutSection;
