/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Navigation from "./Navigation";
import HeroSection from "./HeroSection";
import AboutSection from "./AboutSection";
import TeamSection from "./TeamSection";
import WhyChooseUs from "./WhyChooseUs";
import Statistics from "./Statistics";
import Footer from "./Footer";
import styles from "./CourseDetails.module.css";

function CourseDetails() {
  return (
    <div className={styles.courseDetails}>
      <Header />
      <Navigation />
      <div className={styles.indicator} />
      <HeroSection />
      <AboutSection />
      <TeamSection />
      <WhyChooseUs />
      <Statistics />
      <Footer />
    </div>
  );
}

export default CourseDetails;
