/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

function Header() {
  return (
    <header className={styles.header}>
      <div className={styles.logoContainer}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/c77009e8035674cdb59687b4b8c4ec1149fb57d2e347bffb7ef35c6e64ee6260?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt="ABC School Logo"
          className={styles.logo}
        />
        <h1 className={styles.schoolName}>ABC School</h1>
      </div>
      <div className={styles.contactInfo}>
        <button className={styles.contactButton}>Contact Us</button>
        <div className={styles.phoneContainer}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ada2fc23a9a938e3dce37b9e79851609782e442a3ea3fa3b18d7867d620a2ef5?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
            alt="Phone icon"
            className={styles.phoneIcon}
          />
          <span className={styles.phoneNumber}>(011) 2345 567</span>
        </div>
      </div>
    </header>
  );
}

export default Header;
