/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./HeroSection.module.css";

function HeroSection() {
  return (
    <section className={styles.heroSection}>
      <div className={styles.content}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0b3f2ddf92850e2b03e71e0c3bc060193bb210d7b8bfb5e1a7c01218f7b90ebc?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt="School management system illustration"
          className={styles.heroImage}
        />
        <div className={styles.textContent}>
          <h2 className={styles.title}>
            Best MANAGEMENT SYSTEM FOR YORE Institute
          </h2>
          <button className={styles.exploreButton}>Explore more</button>
        </div>
      </div>
    </section>
  );
}

export default HeroSection;
