/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Navigation.module.css";

function Navigation() {
  const navItems = ["Home", "About Us", "Student Bio", "Payments", "Login"];

  return (
    <nav className={styles.navigation}>
      {navItems.map((item, index) => (
        <a
          key={index}
          href={`#${item.toLowerCase().replace(" ", "-")}`}
          className={styles.navItem}
        >
          {item}
        </a>
      ))}
      <div className={styles.activeIndicator} />
    </nav>
  );
}

export default Navigation;
