/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Statistics.module.css";

function Statistics() {
  const stats = [
    { number: "40+", label: "Live Projects" },
    { number: "50+", label: "Staff" },
    { number: "30+", label: "Satisfied Clients" },
  ];

  return (
    <section className={styles.statistics}>
      {stats.map((stat, index) => (
        <div key={index} className={styles.statItem}>
          <span className={styles.statNumber}>{stat.number}</span>
          <span className={styles.statLabel}>{stat.label}</span>
        </div>
      ))}
    </section>
  );
}

export default Statistics;
