/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./TeamSection.module.css";

function TeamSection() {
  return (
    <section className={styles.teamSection}>
      <h2 className={styles.sectionTitle}>OUR JOURNEY</h2>
      <p className={styles.description}>
        Frithcode was founded with a clear mission: to address the challenges
        faced by schools in managing their daily activities. Our journey began
        with a small team of developers and education enthusiasts who shared a
        common goal – to create intuitive and efficient solutions for schools.
        Over the years, we have grown into a trusted partner for numerous
        educational institutions, continually evolving and improving our
        products to meet the ever-changing needs of the education sector.
      </p>
      <h2 className={styles.sectionTitle}>OUR TEAM</h2>
      <p className={styles.description}>
        Our team is our greatest asset. Comprising skilled professionals from
        diverse backgrounds, we bring together expertise in software
        development, education, and customer support. Each member of our team is
        dedicated to our mission and works tirelessly to ensure that our clients
        receive the best possible service and support.
      </p>
    </section>
  );
}

export default TeamSection;
