/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./WhyChooseUs.module.css";

function WhyChooseUs() {
  return (
    <section className={styles.whyChooseUs}>
      <h2 className={styles.sectionTitle}>WHY CHOOSE US ?</h2>
      <p className={styles.description}>
        Choosing Frithcode means partnering with a company that understands the
        intricacies of school management. Our systems are designed to be
        user-friendly, reliable, and secure. We offer comprehensive support and
        training to ensure that our clients can make the most of our solutions.
        With Frithcode, you can be confident that you are getting a product that
        is tailored to your needs and backed by a team that is dedicated to your
        success.
      </p>
    </section>
  );
}

export default WhyChooseUs;
