/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationForm.module.css";

const RegistrationForm = () => {
  const formFields = [
    { label: "Institute Name", type: "text" },
    { label: "Address", type: "text" },
    { label: "Email", type: "email" },
    { label: "Password", type: "password" },
  ];

  return (
    <section className={styles.registrationSection}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/89b40e7c264e2721e1bbb05e4d985202680f17b5a4890bc1cad0a400d8576032?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
        alt="Registration illustration"
        className={styles.registrationImage}
      />
      <form className={styles.registrationForm}>
        <h2 className={styles.formTitle}>REGISTER</h2>
        <div className={styles.userTypeSelector}>
          <button className={`${styles.userTypeButton} ${styles.active}`}>
            student
          </button>
          <button className={styles.userTypeButton}>teacher</button>
          <button className={styles.userTypeButton}>admin</button>
        </div>
        {formFields.map((field, index) => (
          <div key={index} className={styles.inputGroup}>
            <label htmlFor={`field-${index}`} className={styles.inputLabel}>
              {field.label}
            </label>
            <input
              type={field.type}
              id={`field-${index}`}
              className={styles.inputField}
            />
          </div>
        ))}
        <button type="submit" className={styles.submitButton}>
          SUBMIT
        </button>
      </form>
    </section>
  );
};

export default RegistrationForm;
