/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styles from "./ContactInfo.module.css";

function ContactInfo() {
  return (
    <div className={styles.contactInfoWrapper}>
      <button className={styles.contactButton}>Contact Us</button>
      <div className={styles.contactDetails}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5ee340a4f5368af0cb469c041e714cfbe63a126dcc78fc65b21172d63de3d022?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt="Contact Icon"
          className={styles.contactIcon}
        />
        <div>(011) 2345 567</div>
      </div>
    </div>
  );
}

export default ContactInfo;
