/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styles from "./Footer.module.css";

function Footer() {
  return (
    <footer>
      <div className={styles.footerColumn}>
        <div className={styles.footerLinks}>
          <div className={styles.footerLink}>
            Home
            <br />
            Course Details
            <br />
            Student Bio
            <br />
            Payments
            <br />
            Login
          </div>
          <div className={styles.footerQuickLinks}>Quick links</div>
        </div>
      </div>
      <div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e96e0ee8cde05ebf69f1aee2d1dd1250a547e412a24554aa993df325d4f50236?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt=""
        />
      </div>
      <div className={styles.credit}>
        Website by: Team 1 Frithcode Training Progame
      </div>
      <div className={styles.copyright}>
        ABC School 2011 | All Rights Reserved
      </div>
    </footer>
  );
}

export default Footer;
