/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styles from "./InstituteButton.module.css";

function InstituteButton({ imageUrl, buttonText }) {
  return (
    <div className={styles.instituteButtonWrapper}>
      <img
        loading="lazy"
        src={imageUrl}
        alt=""
        className={styles.instituteImage}
      />
      <button className={styles.instituteButton}>{buttonText}</button>
    </div>
  );
}

export default InstituteButton;
