/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationForm.module.css";

const RegistrationForm = () => {
  const userTypes = ["student", "teacher", "admin"];

  return (
    <section className={styles.registrationSection}>
      <div className={styles.imageContainer}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a1e4fe5aa5c3267eaaf6069099d52a40f01fceed093400d0a30c69afea0d709e?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt="Registration illustration"
          className={styles.registrationImage}
        />
      </div>
      <form className={styles.registrationForm}>
        <h2 className={styles.formTitle}>REGISTER</h2>
        <div className={styles.userTypeSelector}>
          {userTypes.map((type, index) => (
            <button
              key={type}
              type="button"
              className={`${styles.userTypeButton} ${
                index === 0
                  ? styles.start
                  : index === userTypes.length - 1
                  ? styles.end
                  : styles.middle
              }`}
            >
              {type}
            </button>
          ))}
        </div>
        <div className={styles.inputGroup}>
          <label htmlFor="instituteName" className={styles.label}>
            Institute Name
          </label>
          <input type="text" id="instituteName" className={styles.input} />
        </div>
        <div className={styles.inputGroup}>
          <label htmlFor="address" className={styles.label}>
            Address
          </label>
          <input type="text" id="address" className={styles.input} />
        </div>
        <div className={styles.inputGroup}>
          <label htmlFor="email" className={styles.label}>
            Email
          </label>
          <input type="email" id="email" className={styles.input} />
        </div>
        <div className={styles.inputGroup}>
          <label htmlFor="password" className={styles.label}>
            Password
          </label>
          <input type="password" id="password" className={styles.input} />
        </div>
        <button type="submit" className={styles.submitButton}>
          SUBMIT
        </button>
      </form>
    </section>
  );
};

export default RegistrationForm;
