/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../Header/Header";
import RegistrationForm from "../RegistrationForm/RegistrationForm";
import Footer from "../Footer/Footer";
import styles from "./MainComponent.module.css";

const MainComponent = () => {
  return (
    <div className={styles.mainContainer}>
      <Header />
      <main className={styles.mainContent}>
        <RegistrationForm />
      </main>
      <Footer />
    </div>
  );
};

export default MainComponent;
