/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import InstituteButton from "../components/InstituteButton";
import ContactInfo from "../components/ContactInfo";
import Location from "../components/Location";
import Footer from "../components/Footer";
import styles from "./Homepage.module.css";

function Homepage() {
  const instituteData = [
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b0bcb15aba8f96340c9f995b807232c2175f90c9fc7cbb0913a6de8fae6c162b?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4",
      buttonText: "As a school",
    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/419620c5ac889d1ab125ea089f0988f1f33bdb05b62ba0379015828454cdc7d3?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4",
      buttonText: "As a small Institute",
    },
    {
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5b57a0f7365a5b654274582b5308a8ef75c2c30b94b252a04e524cc5b46451c6?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4",
      buttonText: "As a mass Institute",
    },
  ];

  return (
    <>
      <div className={styles.container}>
        <header className={styles.header}>
          <div className={styles.schoolInfo}>
            <div className={styles.schoolBadge} />
            <div>ABC School</div>
          </div>
          <ContactInfo />
        </header>
        <main className={styles.mainSection}>
          <section className={styles.columnsWrapper}>
            {instituteData.map((institute, index) => (
              <div key={index} className={styles.column}>
                <InstituteButton
                  imageUrl={institute.imageUrl}
                  buttonText={institute.buttonText}
                />
              </div>
            ))}
          </section>
          <section className={styles.imageSection}>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad6fdf4b7e1c55862645603dfc82372f7e5ca7d06dfd9073513146c9c9ea84d2?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
              alt="Background"
              className={styles.backgroundImage}
            />
            <div className={styles.imageContent}>
              <div className={styles.columnsWrapper}>
                <div className={styles.column}>
                  {/* Add additional content in here */}
                </div>
                <Location />
              </div>
            </div>
          </section>
        </main>
        <Footer />
      </div>
    </>
  );
}

export default Homepage;
