/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./RegistrationForm.module.css";

const RegistrationForm = () => {
  const userTypes = ["student", "teacher", "admin"];

  return (
    <section className={styles.registrationSection}>
      <div className={styles.imageContainer}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/e6c36c8a0c232d4108c72a88d7b865ca6b937fc0562855bddcf3fdd2b3d4f850?placeholderIfAbsent=true&apiKey=bb53bbd52a344e8a9622d9a748e383b4"
          alt="Registration illustration"
          className={styles.registrationImage}
        />
      </div>
      <form className={styles.registrationForm}>
        <h2 className={styles.formTitle}>REGISTER</h2>
        <div className={styles.userTypeSelector}>
          {userTypes.map((type, index) => (
            <button
              key={type}
              type="button"
              className={`${styles.userTypeButton} ${
                index === 0
                  ? styles.start
                  : index === userTypes.length - 1
                  ? styles.end
                  : styles.middle
              }`}
            >
              {type}
            </button>
          ))}
        </div>
        <InputField label="School Name" />
        <InputField label="Address" />
        <InputField label="Email" type="email" />
        <InputField label="Password" type="password" />
        <button type="submit" className={styles.submitButton}>
          SUBMIT
        </button>
      </form>
    </section>
  );
};

const InputField = ({ label, type = "text" }) => (
  <div className={styles.inputField}>
    <label htmlFor={label.toLowerCase().replace(" ", "-")}>{label}</label>
    <input
      type={type}
      id={label.toLowerCase().replace(" ", "-")}
      name={label.toLowerCase().replace(" ", "-")}
      required
    />
  </div>
);

export default RegistrationForm;
